applist.write=function(applist, listsep=" ", filename=""){
  # Description
  # Write applist to the screen or file
  # Usage
  # applist.write(applist,listsep=" ",filename="")
  # Input:
  # applist: list of appropriatness technologies as generated by app.compute.R 
  # listsep: separato, default=" "
  # filename: output file, if empty string (""), write to standard output, default=""
  
  # auxiliar values
  profilesep=", " #separator for tech.app.profile
  ndigit=2     #number of digits
  
  #Set output mode
  if (filename!="") sink(file=filename, append=FALSE) #redirect cat to file
  
  
  #Write header
  header=paste("case        ", listsep, "tech ",listsep, "tech.app.score", listsep, "tech.app.profile","\n")
  cat(header)
  
  
  #Loop over all element
  for (id in 1:length(applist)){
    elem=applist[[id]]  #list element
    
    #prepare profile list
    profile=elem$tech.app.profile
    profilestr=""     #string to write tech.app.profile
    for (pid in 1:length(profile)){
      if (pid==1){
        profilestr=paste(names(profile[pid]),"=",format(profile[pid],digits=ndigit)) #no separtor for first element
      }else{
        profilestr=paste(profilestr,profilesep,names(profile[pid]),"=",format(profile[pid],digits=ndigit))
      }
    }
    
    #Combine print
    lineout=paste(format(elem$case,width=12),listsep,format(elem$tech,width=12),listsep,format(elem$tech.app.score,digits=ndigit,width=6),listsep,profilestr,"\n")
    cat(lineout)
  }
  if (filename!="") sink(file=NULL) #stop redirection
}
